### ISSUE TITLE
Game binary locations should be configurable

### ISSUE THREAD

**Issue by ghost** [OwenGHB/angband-webclient#1]
The launch paths for the supported games are currently [hardcoded in routes.js](https://github.com/wkmanire/angband-webclient/blob/0081f9f15f52fe86985986443209a4f3b31a0b6c/routes.js#L47-L53). These paths should be configurable per user installation. This is especially useful when you want to test against various builds of a game installed locally but not installed system-wide.

**Comment by OwenGHB** [comment]
supported in games.js
