### ISSUE TITLE
Ability to navigate directly to a player's active game (if there is one)

### ISSUE THREAD

**Issue by ghost** [OwenGHB/angband-webclient#13]
It should be possible to go directly to a player's game using a route like this:

https://angband.live#!/users/wkmanire/activegame

**Comment by OwenGHB** [comment]
Agreed, commenting because the example URL you gave gives me ideas about where to organise the ttyrecs when they arrive.

**Comment by OwenGHB** [comment]
I no longer agree; we don't need this as a feature.
