### ISSUE TITLE
Interesting Statistics to Report

### ISSUE THREAD

**Issue by ghost** [OwenGHB/angband-webclient#15]
It might be interesting to be able to see a view which shows statistics about historical player activity:

- Highest count of users logged in simultaneous
- Current count of living characters
- All time count of dead characters
- How many characters died today?
- How many characters died this year?
- How many total floors explored by all characters (all time, today and year to date)
- Count of deaths by monster and a graph which shows the top 20 deadliest monsters

There are lots of possibilities, but if we want to have a feature like this we'd need to start collecting the data soon.

**Comment by OwenGHB** [comment]
This like so many other things depends on the ability to gather data about the games programmatically - I still think the best way of doing this is reading savefiles.
