### ISSUE TITLE
[feature] Support for keyboards without a keypad

### ISSUE THREAD

**Issue by Thraka** [OwenGHB/angband-webclient#37]
It would be great if you could have a toggle (hotkey and UI) that remapped the keypad keys to 

```
Y U I
H J K
N M <
```

I have a laptop that doesn't have a keypad and I can only play when I'm docked. If I had a quick hotkey like ALT+J or something that would toggle this mode, I think I could be pretty efficient at playing with the shared main keyboard.

**Comment by OwenGHB** [comment]
there's an in-game option to use the 'roguelike keyset' which has hjklyubn mapped to movement keys
