### ISSUE TITLE
Always sort Angband to the top of the list of variants

### ISSUE THREAD

**Issue by peterdresslar** [OwenGHB/angband-webclient#56]
From online chat

**Comment by peterdresslar** [comment]
I could work on this or other items over the Christmas break; it will take me a bit of work to get a couple of variants compiled on my Mac, but I have been able to build the project itself locally.

**Comment by peterdresslar** [comment]
for instance, this could work:

https://gist.github.com/peterdresslar/216996e43342e8de09ba5c038e2b3f4d

can try inserting into lib.js tomorrow

**Comment by OwenGHB** [comment]
I think I will take care of this. Perhaps you could experiment with
xterm.js instead?

**Comment by peterdresslar** [comment]
Sure, although I could really use some help with a few compiled *bands. I think I am going to need to set up a docker environment on my mac to safely test xterm.

**Comment by OwenGHB** [comment]
Turns Out AlexAngband is going to be non-trivial to compile, so this can wait. Check out my 2.9.3L, Kangband 2.9.3L, and Composband repos for bands that will compile without a lot of fuss.. I don't think you'll need docker

**Comment by peterdresslar** [comment]
Thanks, not surprised about AlexAngband.
 I have to swap computers this week as it turns out, so I will take a bit
of time on the terminal swap. Hope you are feeling better.

**Comment by OwenGHB** [comment]
Fixed
